#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S3, HTMotor,  HTServo,  HTServo,  none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSPB,          sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTMUX,          sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     BackL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Flapper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     BackR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     FrontR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C1_1,     FanR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     FanL,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C2_1,    trailerR,             tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    trailerL,             tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    lift,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    rakes,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    flap,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    servo12,              tServoStandard)
#pragma config(Servo,  srvo_S3_C3_1,    servo13,              tServoStandard)
#pragma config(Servo,  srvo_S3_C3_2,    spout,                tServoStandard)
#pragma config(Servo,  srvo_S3_C3_3,    faucet,               tServoStandard)
#pragma config(Servo,  srvo_S3_C3_4,    servo16,              tServoStandard)
#pragma config(Servo,  srvo_S3_C3_5,    servo17,              tServoStandard)
#pragma config(Servo,  srvo_S3_C3_6,    servo18,              tServoStandard)
#pragma config(Servo,  srvo_S4_C1_1,    foldRoller,           tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    roller,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo21,              tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo22,              tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo23,              tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo24,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "PhiloDefs.h"
#include "PhiloUtils.h"
#include "CenterGoalUs.h"
WestCoaster g_wcDrive;

void initializeRobot()
{
  WestCoaster_init(g_wcDrive,FrontL, FrontR, BackL, BackR, FrontL, FrontR);
  WestCoaster_initMPU(S2);
	servo[lift] = LIFT_BOTTOM;
	motor [Flapper] = 0;
	pinClosed();
	servo[foldRoller] = ROLLER_FOLDER_UP;
	servo[roller] = 126;
	faucetInitial();
	//move servos at maximium speed
	servoChangeRate[trailerL]=0;
	servoChangeRate[trailerR]=0;
	servoChangeRate[lift]=0;

	//set to true during competition to keep the grabber engaged
	bSystemLeaveServosEnabledOnProgramStop=true;

}

task main()
{
	initializeRobot();
  driveToGoal(g_wcDrive, CENTER_GOAL_SONAR, 20, 30);
  //did we find the center goal?
}
