#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTServo,  HTServo,  none)
#pragma config(Sensor, S4,     HTMUX,          sensorI2CCustomFastSkipStates9V)
#pragma config(Motor,  mtr_S1_C1_1,     BackL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     MidR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     MidL,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     FrontR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C1_1,     FanR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     FanL,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    flapper1,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    flapper2,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_1,    trailerR,             tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    trailerL,             tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    lift,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    rakes,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    flap,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    faucet,               tServoStandard)
#pragma config(Servo,  srvo_S3_C3_1,    flapper3,             tServoStandard)
#pragma config(Servo,  srvo_S3_C3_2,    servo14,              tServoNone)
#pragma config(Servo,  srvo_S3_C3_3,    servo15,              tServoNone)
#pragma config(Servo,  srvo_S3_C3_4,    servo16,              tServoNone)
#pragma config(Servo,  srvo_S3_C3_5,    servo17,              tServoNone)
#pragma config(Servo,  srvo_S3_C3_6,    servo18,              tServoNone)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define KICK_AND_GOAL
#include "PhiloDefs.h"
#include "WestCoaster.h"
#include "CenterGoalUs.h"
#include "JoystickDriver.c"
WestCoaster g_wcDrive;

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  //servo[flap]=255;//close flap
  WestCoaster_init(g_wcDrive,FrontL, FrontR, MidL, MidR, BackL, BackR, FrontL, FrontR);
  return;
}
void kickFromParking(int goalPosition)
{

  if(goalPosition == 1){
  	WestCoaster_straightMove(g_wcDrive,-38);
    sleep(100);
		WestCoaster_encoderObservedTurn(g_wcDrive,-135);
		sleep(100);

		WestCoaster_forwardFullSpeed(g_wcDrive,-24);
  }
	else if(goalPosition == 2){
		WestCoaster_straightMove(g_wcDrive,-29);
    sleep(100);
		WestCoaster_encoderObservedTurn(g_wcDrive,-70);
		sleep(100);
		WestCoaster_forwardFullSpeed(g_wcDrive,-48);
	}
	else if(goalPosition ==3){
		WestCoaster_straightMove(g_wcDrive,-28);
    sleep(500);
	  WestCoaster_encoderObservedTurn(g_wcDrive,-90);
		sleep(-100);
		WestCoaster_straightMove(g_wcDrive,-15);
    sleep(200);
		WestCoaster_encoderObservedTurn(g_wcDrive,100);
		sleep(100);
		WestCoaster_forwardFullSpeed(g_wcDrive,-48);
	}
}
void kickFromGoal()
{
	//TODO: roughly something like:
  //back off a little
  WestCoaster_straightMove(g_wcDrive,-8);
  // turn right 90
  WestCoaster_encoderObservedTurn(g_wcDrive,-90);
  // move to the side a little
  WestCoaster_straightMove(g_wcDrive, -8);
    // turn left 90
  WestCoaster_encoderObservedTurn(g_wcDrive,90);
    // straight ahead to kick at full speed
  WestCoaster_forwardFullSpeed(g_wcDrive, -40);
}
//get very close to the center goal using encoders
void closeToCenterGoal(int goalPosition)
{
	//TODO
}

//drop ball to
void deposit()
{ //TODO
}

task main()
{
	initializeRobot();
//	waitForStart();
  int distance=0;

  WestCoaster_straightMove(g_wcDrive,-4);
  //we only need 100ms or less to determine the center goal
  //orientation./*
  int goalPosition = determineGoalPosition(CENTER_GOAL_SONAR, 100);
	/* Display Sonar Sensor values */

  distance = readDist(CENTER_GOAL_SONAR);
	displayCenteredTextLine(0, "Goal: %d", goalPosition);
	displayCenteredTextLine(1, "distance: %d", distance);
#ifndef 	KICK_AND_GOAL
  kickFromParking(goalPosition);
#else
  //get very close using only encoders
	closeToCenterGoal(goalPosition);
	//fine alignment using sonar
	driveToGoal(g_wcDrive, CENTER_GOAL_SONAR, 10, 15);
	deposit();
	//got to kickstand
	kickFromGoal();
#endif
}
