#pragma config(Sensor, S4,     ,               sensorI2CCustomFastSkipStates9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "PhiloDefs.h"
#include "CenterGoalUs.h"
task main()
{
	while(true){
		sleep(200);

#ifdef USE_HT_SENSOR_MUX
		int distL= readDist(CENTER_GOAL_SONAR);
		int distR = USreadDist (msensor_S4_2);
#else
		int distL=SensorValue[sonarSensorL];
		int distR=SensorValue[sonarSensorR];
#endif
		writeDebugStreamLine("left: %d, right: %d",distL, distR);
		int position=determineGoalPosition(msensor_S4_3, 50);
		writeDebugStreamLine("goalPosition: %d",position);
	}
}
