#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     BackL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     MidR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     MidL,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     FrontR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C1_1,     FanR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     FanL,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    flapper1,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    flapper2,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_1,    trailerR,             tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    trailerL,             tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    lift,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    rakes,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    flap,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    faucet,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ultraSoundAutonomous.c"
#include "gyro-encoder_fused.c"
#include "JoystickDriver.c"

//fanon
//grabgoal
//
task main()
{
	waitForStart();
  int distance=0;

  straightMove(-3);
  sleep(1000);
  //we only need 100ms or less to determine the center goal
  //orientation.
  int goalPosition = determineGoalPosition(sonarSensor, 100);
	/* Display Sonar Sensor values */
  distance = SensorValue[sonarSensor];
	displayCenteredTextLine(0, "Goal: %d", goalPosition);
	displayCenteredTextLine(1, "distance: %d", distance);

  if(goalPosition == 1){
  	straightMove(-38);
    sleep(100);
		encoderObservedTurn(-115);
		sleep(100);
		straightMove(-24);
  }
	else if(goalPosition == 2){
		straightMove(-29);
    sleep(100);
		encoderObservedTurn(-70);
		sleep(100);
		straightMove(-48);
	}
	else if(goalPosition ==3){
		straightMove(-28);
    sleep(500);
	  encoderObservedTurn(-90);
		sleep(100);
		straightMove(-15);
    sleep(200);
		encoderObservedTurn(70);
		sleep(100);
		straightMove(-48);
	}

}
