#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     BackL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     FrontR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     FanR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     FanL,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    intake,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    rakes,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    insertion,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    faucet,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int leftJoy=0;
int rightJoy=0;

void moveAround(int rawLeftJoy, int rawRightJoy){



	//movement

	if(abs(rawLeftJoy/128.0*100) > 5)
		leftJoy=rawLeftJoy/128.0*100;
	else
		leftJoy = 0;
	if(abs(rawRightJoy/128.0*100) > 5)
		rightJoy=rawRightJoy/128.0*100;
	else
		rightJoy = 0;

	motor[FrontR] =-rightJoy;
	motor[FrontL] = leftJoy;
	motor[BackR] = -rightJoy;
	motor[BackL] = leftJoy;

}
void controlFans(bool fan){
	if(!fan){
		return;
	}
	static bool wasOnLastTime = false;
	if(fan && !wasOnLastTime){
		motor[FanL] = 60;
		motor[FanR] = -60;
		wasOnLastTime = true;
	}
	else{
		motor[FanL] = 0;
		motor[FanR] = 0;
		wasOnLastTime = false;
	}
}
void moveBelt(bool intakeChoice)
{ if (!intakeChoice)
		return;
	static bool wasOnLastTime = false;
	if (wasOnLastTime)
	{
		servo[intake] = 0;
		wasOnLastTime = false;
	}
	else
	{
		servo [intake] = 128;
		wasOnLastTime = true;
	}
}

void moveRakes(bool rakeChoice)
{ if (!rakeChoice)
		return;
	static bool wasOnLastTime = false;
	if (wasOnLastTime)
	{
		servo[rakes] = 128;
		wasOnLastTime = false;
	}
	else
	{
		servo [rakes] = 255;
		wasOnLastTime = true;
	}

}
void moveInsertion(bool insertChoice)
{
	if (!insertChoice)
		return;
	static bool wasOnLastTime = false;
	if (wasOnLastTime)
	{
		servo[insertion] = 10;
		wasOnLastTime = false;
	}
	else
	{
		servo [insertion] = 250;
		wasOnLastTime = true;
	}

}
void moveFaucet(bool faucetRight, bool faucetLeft)
{
	if (!faucetRight && ! faucetLeft){
		servo [faucet] = 127;
		return;
	}
	else if(faucetRight){
		servo [faucet] = 255;
		}else if(faucetLeft){
		servo [faucet] = 0;
	}
}

volatile bool flap_pressed=false;
long last_flap_time=0;
task joy()
{
	while(true)
	{
		getJoystickSettings(joystick);
		hogCPU();
		if(joy1Btn(4)
			&&
	    (!flap_pressed)
	    && ((nSysTime-last_flap_time)>500)
			) {
				flap_pressed=true;
				last_flap_time=nSysTime;
			}
		releaseCPU();
	}
}

task main()
{
	//waitForStart();   // wait for start of tele-op phase
	startTask(joy);
	//set everything
	while (true)
	{

		int rawLeftJoy=joystick.joy1_y1;
		int rawRightJoy=joystick.joy1_y2;


		moveAround(rawLeftJoy, rawRightJoy);
		controlFans(joy1Btn(2));
		moveBelt(joy1Btn(3));
		moveRakes(joy1Btn(6));

		if(flap_pressed) {
			writeDebugStreamLine("flap pressed");

			moveInsertion(true);
			hogCPU();
			flap_pressed=false;
			releaseCPU();
		}
		moveFaucet(joy1Btn(8), joy1Btn(9));
		sleep(10);

	}

}
