#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     Gyro,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     FrontL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BackL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     FrontR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveForward(int t, int power){

	clearTimer(T1);
	while(time1[T1] <= t){
		motor[FrontR] = -power;
		motor[FrontL] = power;
		motor[BackR] = -power;
		motor[BackL] = power;
	}

}
void turnLeft(int t){
	clearTimer(T1);
	while(time1[T1] <= t){
		motor[FrontR] = -100;
		motor[FrontL] = -100;
		motor[BackR] = -100;
		motor[BackL] = -100;
	}
}

task main()
{
	//waitForStart();
	driveForward(2250, 100);
	turnLeft(540);

}
