#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     BackL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     FrontR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "gyro-encoder_fused.c"
#include "ultraSoundAutonomous.c"
task main()
{
	//waitForStart();
  straightMove(63);
//	startTask(gyro_loop);
//	while(gyro_loop_state!=READING) sleep(5);

  //sleep(50);
  //encoderObservedTurn(180);
  sleep(1000);
  encoderObservedTurn(90);

  //sleep(5000);
  //	encoderObservedTurn(-90);  //encoderPredictionTurn(-90);
  /*sleep(2000);
	int goalPosition = determineGoalPosition();
	displayCenteredTextLine(0, "Goal Position");       /* Display Sonar Sensor values */
  /*displayCenteredBigTextLine(2, "%d", goalPosition);
  displayCenteredTextLine(4, "dist:%d", distance);
	sleep(5000);


  if(goalPosition == 1){
		straightMove(30);
		sleep(100);
		gyroTurn(-90);
		sleep(100);
		straightMove(23);
		sleep(100);
		gyroTurn(-90);
		sleep(100);
		straightMove(48);
		sleep(100);
  }
	else if(goalPosition == 2){
		straightMove(180);
		gyroTurn(90);
	}
	else{
		encoderTurn(45);
		sleep(50);
		straightMove(85);
    sleep(50);
		encoderTurn(-100);
		sleep(50);
		straightMove(36);
	}*/
}
