#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     BackL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BackR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     FrontR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	//waitForStart();   // wait for start of tele-op phase

	//set everything
	int leftJoy=0;
	int rightJoy=0;

	while (true)
	{

		getJoystickSettings(joystick);

		int rawLeftJoy=joystick.joy1_y1;
		int rawRightJoy=joystick.joy1_y2;


		//movement

		if(abs(rawLeftJoy/128.0*100) > 5)
			leftJoy=rawLeftJoy/128.0*100;
		else
			leftJoy = 0;
		if(abs(rawRightJoy/128.0*100) > 5)
			rightJoy=rawRightJoy/128.0*100;
		else
			rightJoy = 0;

		motor[FrontR] =-rightJoy;
		motor[FrontL] = leftJoy;
		motor[BackR] = -rightJoy;
		motor[BackL] = leftJoy;


	}

}
