#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S4_C1_1,    intake,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		Servo[intake]=0;
	}

}
